repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.7.1
      hooks:
        - id: ruff
          args: [ --fix ]
        - id: ruff-format
    - repo: local
      hooks:
        - id: mypy
          name: mypy
          language: python
          entry: bash -c "mypy ."
          pass_filenames: false
